* kamelcase

  This is a -- yet another -- super-simple monkeypatch of the
  String class to offer both camelCase and snake_case.

** Installing

   From the command-line:
   #+begin_src bash
   gem install kamelcase
   #+end_src

   From your gemfile:
   #+begin_src ruby
   gem 'kamelcase', '~> 0'
   #+end_src

** Usage and Examples
   #+begin_src ruby
   require 'kamelcase'
   s = 'little green men'

   puts s.camel             # LittleGreenMen
   puts s.camel_lower       # littleGreenMen
   puts s.snake             # little_green_men
   puts s.camel.snake       # little_green_men
   puts s.snake.camel       # LittleGreenMen
   puts s.snake.camel_lower # littleGreenMen
   #+end_src

** Contributing to kamelcase
 
   - Check out the latest master to make sure the feature hasn't been implemented or the bug hasn't been fixed yet.
   - Check out the issue tracker to make sure someone already hasn't requested it and/or contributed it.
   - Fork the project.
   - Start a feature/bugfix branch.
   - Commit and push until you are happy with your contribution.
   - Make sure to add tests for it. This is important so I don't break it in a future version unintentionally.
   - Please try not to mess with the Rakefile, version, or history. If you want to have your own version, or is otherwise necessary, that is fine, but please isolate to its own commit so I can cherry-pick around it.

** Copyright

   Copyright (c) 2017 Fred Mitchell. See LICENSE.txt for
   further details.
